plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'net.fabricmc.fabric-loom' version '1.15.5' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.141' apply false
}

tasks.register("printEnv") {
    doLast {
        def envFile = new File(System.getenv("GITHUB_ENV"))
        envFile.append("MOD_VERSION=${project.version}\n")
        envFile.append("RELEASE_NAME=${project.mod_name}-${project.version}\n")
        envFile.append("GAME_VERSIONS=${project.minecraft_version_range}\n")
    }
}

subprojects {
    repositories {
        maven {
            url "https://libraries.minecraft.net"
            content {
                includeModule("org.lwjgl", "lwjgl-freetype")
                includeGroup("com.mojang")
            }
        }
    }
}