# Project
version=1.0
group=net.anvian.usedtotemmessage
java_version=25

# Common
minecraft_version=26.1
mod_name=UsedTotemMessage
mod_author=anvian
mod_id=usedtotemmessage
license=GPL-3.0
credits=
description=This mod will send a message to all players when a player uses a totem of undying.
minecraft_version_range=[26.1, 26.2)
neo_form_version=26.1-1

# Fabric
fabric_version=0.144.0+26.1
fabric_loader_version=0.18.4

# NeoForge
neoforge_version=26.1.0.19-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

anvianslib=1.4.1
